Redux Branch
stanleySimeon/bookstore pull request #2
Opened 2022-04-19 17:06 UTC by stanleySimeon

# In this milestone I added:

  # Redux Component that contains:
   - a books folder, inside it books.js
   - a categories folder, inside it cotegories.js
   - and I add some features to the CSS file.

2022-04-19 20:08 UTC, mikethreels requested changes
Hi Stanley, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] please make sure to use [the template](https://github.com/microverseinc/readme-template) for the readme file provided by Microverse, including the links (for example to the MIT license). keep in mind that all sections of the template are mandatory except for the "Live Demo", "Run Tests" and "Deployment" sections, these are only mandatory if the specific project you're working on requires it.
- [ ] you've added the `configureStore.js` which is great it seems like you forgot to add the content of the file as mentioned in the requirements:

- Configure the Redux Store (/src/redux/configureStore.js):

  - Importing the necessary methods from Redux.
  - Combine both reducers into a root reducer by using the `combineReducers` function.
  - Use the root reducer to create your store.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-19 20:08 UTC, mikethreels commented on src/Redux/books/books.js
> +      };
- [ ] in case the `action.type` is `REMOVE_BOOK` you should use the filter method, which will look something like:
```
return state.filter(book => book.id !== id); 
```

2022-04-19 20:08 UTC, mikethreels commented on src/Redux/categories/categories.js
> +      return { ...state, status: action.payload };
- [ ] according to the requirements in case action.type is CHECK_STATUS the function should return a string "Under construction".

2022-04-20 05:41 UTC, Emmyn5600 approved these changes
Hi @stanleySimeon 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: :clap: :clap: :100:

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions

- [ ] N/A

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-20 06:04 UTC, merged